export enum collections {
  QUANTITY_RESULTS_TRADITIONAL = 'quantityResultsTraditional',
  QUANTITY_RESULTS_REVANCHA = 'quantityResultsRevancha',
  QUANTITY_BALOTA_TRADITIONAL = 'quantityBalotaTraditional',
  QUANTITY_BALOTA_REVANCHA = 'quantityBalotaRevancha',
  RESULTS_SINCE_LAST_TRADITIONAL = 'resultsSinceLastTraditional',
  RESULTS_SINCE_LAST_REVANCHA = 'resultsSinceLastRevancha',
  BALOTA_SINCE_LAST_TRADITIONAL = 'balotaSinceLastTraditional',
  BALOTA_SINCE_LAST_REVANCHA = 'balotaSinceLastRevancha',
  RESULTS_TRADITIONAL = 'resultsTraditional',
  RESULTS_REVANCHA = 'resultsRevancha',
  RESULTS_AVERAGE_OF_NOT_SHOWING_UP_TRADITIONAL = 'resultsAverageOfNotShowingUpTraditional',
  RESULTS_AVERAGE_OF_NOT_SHOWING_UP_REVANCHA = 'resultsAverageOfNotShowingUpRevancha',
  BALOTA_AVERAGE_OF_NOT_SHOWING_UP_TRADITIONAL = 'balotaAverageOfNotShowingUpTraditional',
  BALOTA_AVERAGE_OF_NOT_SHOWING_UP_REVANCHA = 'balotaAverageOfNotShowingUpRevancha',
};
